---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: apps-repo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/dvbgm/apps-repo.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-repo
  namespace: flux-system
spec:
  interval: 10m0s
  path: "./"
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps-repo